### ISSUE TITLE
Bjarne Stroustrup - Video not loading 

### ISSUE THREAD

**Issue by jenipdang** [learn-co-curriculum/react-hooks-components-basics#5] opened 2021-11-16 06:50 UTC
### Canvas Link

https://learning.flatironschool.com/courses/4696/assignments/138212?module_item_id=286963

### Concern

The embed Bjarne Stroustrup video is not loadin
![Screen Shot 2021-11-15 at 10 48 28 PM](https://user-images.githubusercontent.com/75016280/141935493-cef791f6-0cac-4ffc-b7af-0d122b000e40.png)
g

**Comment by lizbur10** [comment] 2021-11-18 13:10
Hi @jenipdang ! I am not able to reproduce this issue - the video is loading for me. It may have just been a temporary service issue. I'm going to go ahead and close the issue but if you continue to have problems feel free to reopen it. 💙

**Closed by lizbur10** 2021-11-18 13:10 UTC
Labels: se curriculum
